### ISSUE TITLE
"Meta" Helm chart for ORC

### ISSUE THREAD

**Issue by MridulS** [gesiscss/orc#13]
We have now helm chart for [gesis binder](https://github.com/gesiscss/orc/tree/master/gesisbinder/gesisbinder) and [gesis hub](https://github.com/gesiscss/orc/tree/master/gesishub). 

* [ ]  Learn more about helm releases and rollback
* [ ]  Make helm chart for gallery
* [ ]  Make helm chart for orc-site -> here mount html templates as configmaps too
* [ ]  Finally make a orc helm chart for whole project (similar to mybinder.org-deploy chart), which requires all other charts/apps (including storage, monitoring, gesis binder, hub, gallery charts...). So we can have 1 values.yaml for whole project?
            - For example we can also have GESIS templates (and statics?) in a configmap and all apps use that configmap.
